### ISSUE TITLE
Checklist for 0.4.0

### ISSUE THREAD

**Issue by bamorim** [bamorim/typed_ecto_schema#19]
- [x] Fix compile time dependencies (Fixed in #18)
- [x] Support custom source schema assocs (Fixed in #18)
- [x] Fix the typing for `TypedEctoSchema.EctoTypeMapper.base_type_for/2` since now it always receive the AST so it should probably be `Macro.t()`
- [x] Remove config folder (we don't use for anything)
- [ ] Regression test for compile time dependencies
- [x] Properly support inline defined embeds (Related to #11)

**Comment by bamorim** [comment]
@dvic are you missing something?

For the regression test my initial thought was to just create a subproject and run `mix xref --format cycles --label compile` and see if it returned no cycles.

A more complex solution would be to use [Compilation tracers](https://hexdocs.pm/elixir/1.13/Code.html#module-compilation-tracers), but I still have to learn how to use it so it could take longer.

**Comment by dvic** [comment]
> @dvic are you missing something?

Not sure if I mentioned this before, but with Ecto master version using `null: false` introduces a compile error. I think it's being passed to Ecto and now they validate the options. Maybe we could add this as well to 0.4? (I think it's a small fix)

> For the regression test my initial thought was to just create a subproject and run `mix xref --format cycles --label compile` and see if it returned no cycles.
> 
> A more complex solution would be to use [Compilation tracers](https://hexdocs.pm/elixir/1.13/Code.html#module-compilation-tracers), but I still have to learn how to use it so it could take longer.

I agree we can go with a subproject for now, this is what we use in our projects:

```bash
mix xref graph --label compile-connected --format stats \
    --exclude some_path \ # if some paths should be ignored
    | grep "Compile dependencies: 0"
```

**Comment by dvic** [comment]
Just submitted #23, another thing to mark from the checklist :)

By the way: you can complete also ` Remove config folder` right?
